Added room creation, room switching, and messaging
UCSD-MASHED/chatapp pull request #23
Opened 2020-11-29 01:19 UTC by edwjchen

## Checklist

- [x] Did you write tests for your code?
- [x] Did all the tests pass locally?

## Trello Ticket
https://trello.com/c/VMEo6eNw/27-uc3-coding
https://trello.com/c/GIZ9sKqv/28-uc3-testing
https://trello.com/c/O5vemg6b/29-uc3-docs

https://trello.com/c/5zp3IZUg/46-room-creation-coding
https://trello.com/c/Og8g8hKu/47-room-creation-testing

## Short Description

See header

## Reviewer Notes

Anything special you want the reviewer to know?

2020-11-29 20:40 UTC, Joyfal requested changes
Overall looks pretty good! Dropped some comments and questions.

2020-11-29 20:40 UTC, Joyfal commented on package.json
> +    "react": "^16.14.0",
We probably can use react 17 now since we no longer need enzyme?

2020-11-29 20:40 UTC, Joyfal commented on src/modules/ChatRoom.js
> +      await this.getFirstRoom();
Is this the behavior we want? (I think maybe just show an empty page to replace the "chat room" when we first enter ChatRoom is better, but I am open to ideas)

2020-11-29 20:40 UTC, Joyfal commented on src/modules/User.js
> +        .then(function (roomRef) {
NIT: 

`.then((roomRef) => roomRef.id)`

2020-11-29 20:40 UTC, Joyfal commented on src/modules/ChatRoom.js
> +    this.initMessages = true;
I don't think we need this variable anymore?

2020-11-29 23:33 UTC, macedo22 commented on src/modules/ChatRoom.js
> +    this.initMessages = true;
I think I agree with this, since I believe this function will only ever run once to my understanding

2020-11-30 03:40 UTC, edwjchen commented on src/modules/ChatRoom.js
> +      await this.getFirstRoom();
To give a bit of clarity, it will only show this chatroom iff the user and the first user has already had a conversation. Otherwise, this will show an "empty room" page. 

This mimics messenger's behavior so I'm an advocate for keeping it!

2020-11-30 03:41 UTC, edwjchen commented on src/modules/User.js
> +        .then(function (roomRef) {
wow js is so weird 👀

2020-11-30 10:03 UTC, macedo22 requested changes
I left some ideas for significant changes to the `ChatRoom` tests. In looking at my suggested changes for these tests, it makes most sense to first check out my comment on the new `Switch rooms` test you added. I realize that this PR was more about room creation than `ChatRoom` testing at large, so when you take a look at some of the change suggestions for those, if you do agree with them, then let me know if you think it's more appropriate to defer them to the PR I will submit after this that adds a unit test for `sendMessage`.

Regardless, if you do agree with the idea of my change suggestions to the tests, then note that after adding a couple suggested new implementations for a couple of the tests in my comments, I realized that a good chunk of what I recommend changing is consistent for all the unit tests for `ChatRoom`: separating the mocked data and results from individual calls to `get`. Namely, the first three calls to `get` in `getUsers`, `getFirstRoom`, and `getInitMessages` are the same for each chatroom test. So if we do go with the changes I'm proposing, we either might want to move some of this redundant stuff to `beforeEach`. If not, we can just repeat it in each test.

Let me know your thoughts!

2020-12-01 01:33 UTC, Joyfal commented on src/modules/ChatRoom.js
>          this.getInitMessages().then(() => {
If we use .then(), we don't need async/await.

2020-12-01 01:40 UTC, macedo22 commented on src/modules/ChatRoom.js
>          this.getInitMessages().then(() => {
hmm for some reason I thought I experienced different behavior locally when running tests. But, I just reran things and think I was mistaken. My bad - ignore this! Thanks @Joyfal

2020-12-03 07:36 UTC, merged

2020-12-03 07:49 UTC, Joyfal reviewed
some NITs

2020-12-03 07:49 UTC, Joyfal commented on src/__tests__/ChatRoom.test.js
> +  user.roomIds = []; // set back to empty for other tests
maybe move this to `beforeEach` ?

2020-12-03 07:49 UTC, Joyfal commented on src/modules/ChatRoom.js
> +      console.log(this.state.users);
let's get rid of comments (comment them out at least)

2020-12-03 07:49 UTC, Joyfal commented on src/modules/ChatRoom.js
> +    /**
The headers also has to be above the functions. Please refer to slack messages for details and extra requirements (if there is any).

2020-12-03 07:49 UTC, Joyfal commented on src/__tests__/ChatRoom.test.js
> +  console.log("Starting test: Search user");
comment out logs