Updating landing page!
UCSD-MASHED/chatapp pull request #35
Opened 2020-12-06 13:21 UTC by edwjchen

## Checklist
No tests applicable
- [ ] Did you write tests for your code?
- [ ] Did all the tests pass locally?

## Trello Ticket
n/a

## Short Description
Updated landing page!

What does this PR contain?

## Reviewer Notes

Anything special you want the reviewer to know?

2020-12-06 18:30 UTC, albinencio commented
I just looked at the preview. Love it! Only suggestion I have is to move the Log In button maybe under the text fields, and make it a tiny bigger? Having it so small and in the corner doesn't quite match with the importance of the function of that button. Just an opinion open for discussion. Also... let's def merge this if we can cause it makes the whole thing look a lot more professional.

2020-12-06 19:09 UTC, Joyfal requested changes
I agree with Alberto that we should move the sign in button the the body of the landing page and make it bigger. Besides this, it looks good!

2020-12-06 19:09 UTC, Joyfal commented on src/modules/ChatRoom.js
> +        <div className="btn-wrapper">
why was this renamed? It's actually a chat wrapper, not just a button wrapper. It wraps the button and many more stuff.

2020-12-06 23:07 UTC, edwjchen commented
> I just looked at the preview. Love it! Only suggestion I have is to move the Log In button maybe under the text fields, and make it a tiny bigger? Having it so small and in the corner doesn't quite match with the importance of the function of that button. Just an opinion open for discussion. Also... let's def merge this if we can cause it makes the whole thing look a lot more professional.

The login button matches the logout button if its here like this, but I'm open to changing it as well

2020-12-07 00:44 UTC, edwjchen commented on src/modules/ChatRoom.js
> +        <div className="btn-wrapper">
mb I thought the wrapper was just for the logout button, and I wanted to make the signin and logout buttons consistent

2020-12-07 00:48 UTC, albinencio commented
> > I just looked at the preview. Love it! Only suggestion I have is to move the Log In button maybe under the text fields, and make it a tiny bigger? Having it so small and in the corner doesn't quite match with the importance of the function of that button. Just an opinion open for discussion. Also... let's def merge this if we can cause it makes the whole thing look a lot more professional.
> 
> The login button matches the logout button if its here like this, but I'm open to changing it as well

Yeah I imagined you put it there for that reason. We can see in meeting if the team has a preference. I'm still leaning more towards moving it to the body.

2020-12-07 02:20 UTC, Joyfal commented on src/modules/Jokes.js
> +    console.log(props);
NIT: get rid of all console.logs

2020-12-07 02:23 UTC, Joyfal commented on src/modules/Login.js
> +              <h1>TaterTalk</h1>
We can probably add one simple test for this text.

2020-12-07 02:25 UTC, Joyfal commented on src/modules/Login.js
> +              src={process.env.PUBLIC_URL + "/landing_illustration.png"}
you can import the logo image and use it here: see example: https://github.com/UCSD-MASHED/chatapp/blob/main/src/App.js#L8

2020-12-07 02:55 UTC, edwjchen commented on src/modules/Login.js
> +              <h1>TaterTalk</h1>
Oo good point!

2020-12-07 03:00 UTC, edwjchen commented on src/modules/Login.js
> +              src={process.env.PUBLIC_URL + "/landing_illustration.png"}
This only works if the images are in the src folder instead of the public folder, do you want me to move it? I don't exactly know the benefit of one implementation vs. the other

2020-12-07 03:04 UTC, Joyfal commented on src/modules/Login.js
> +              src={process.env.PUBLIC_URL + "/landing_illustration.png"}
I just felt like this might introduce bug/problems (looks odd to me). But I don't think this is the case after some research, what you have is totally fine.

2020-12-07 04:44 UTC, Joyfal approved these changes
LGTM

2020-12-07 05:12 UTC, merged