Add Cypress tests for messaging and room change
UCSD-MASHED/chatapp pull request #36
Opened 2020-12-06 18:45 UTC by macedo22

## Checklist

- [x] Did you write tests for your code?
- [x] Did all the tests pass locally?

## Trello Ticket

https://trello.com/c/cM6N9VLN/49-cypress-end-to-end-testing

## Short Description

This PR adds 3 tests for testing the functionality of messaging and switching rooms:
1. Makes sure a user is not dropped into the first room if they don't already belong to a room with the first user in the user list, and makes sure they can't send a message.
2. Checks that, upon choosing a user from the user list, the room name is the display name of that user and that existing messages are populated.
3. Checks that, upon choosing a user form the user list, a received message and a sent message render. Then, the current user switches to a new room and repeats this.

## Reviewer Notes

Anything special you want the reviewer to know?

2020-12-06 19:24 UTC, Joyfal requested changes
looks good, some NITs.

2020-12-06 19:24 UTC, Joyfal commented on cypress/integration/chatRoom.spec.js
> +    cy.get('[data-testid="room-name"]').should(
why don't we use ` cy.get('[data-testid="room-name"]').contains()` here? It seems easier.

2020-12-06 19:24 UTC, Joyfal commented on cypress/integration/chatRoom.spec.js
> +    cy.get('[data-testid="room-name"]').should(
Same comment as the last one

2020-12-06 19:32 UTC, Joyfal commented on src/modules/ChatRoom.js
>            qs.forEach((doc) => {
One more NIT: since we know the query result is of length 1. We can use
`const room = qs.docs[0].data()` to get the actual room we need rather than doing a `forEach`.

2020-12-08 10:54 UTC, macedo22 commented
@Joyfal I think your comments are addressed. Also, since the previous commits already had some fixes to the "Render user list" and "Search user" tests, I added an extra commit that just took care of a couple loose ends to clean them up a bit more since we merged our combined work on this

2020-12-08 19:36 UTC, Joyfal approved these changes
LGTM

2020-12-08 19:42 UTC, InnocenceD approved these changes
lgtm

2020-12-08 19:45 UTC, merged