Update readme
UCSD-MASHED/chatapp pull request #53
Opened 2020-12-12 23:51 UTC by Joyfal

## Checklist

- [N/A] Did you write tests for your code?
- [N/A] Did all the tests pass locally?

## Trello Ticket
https://trello.com/c/QKww7c9H/87-update-readme-onboarding-doc

## Short Description
See ticket above.

## Reviewer Notes
Please let us know what do you think/what is missing.

2020-12-13 02:25 UTC, albinencio requested changes
Added few comments. Another thing you can do is try to move the [tech stack file](https://docs.google.com/document/d/1bA7HUU-yUjH8upib4j-9lAYjdoZgPeE2zDTzQcr4Blo/edit) content to the README, so we can get rid of the file. In particular, I'd put it after Architecture but before Setup. If it becomes to cluttered we can always move some things to GitHub Wiki. Basically as long as we have it written in MD it won't be hard to move it away from README.

2020-12-13 02:25 UTC, albinencio commented on README.md
> +This project was bootstrapped with [Create React App](https://github.com/facebook/create-react-app) and utilizes [Firebase](https://firebase.google.com/).
Add brief app description.

2020-12-13 02:25 UTC, albinencio commented on README.md
> +## Setup
We should probably distinguish two paths for setup: one if you are trying to just clone this repo and add to the existing code, one if you are trying to replicate the app from scratch. Most of things will overlap so we can just include them once. But for example for someone just using this repository, they don't need to create a separate Firebase app. @macedo22 lmk what you think

2020-12-13 02:25 UTC, albinencio commented on README.md
> +`*_APIKEY`, `*_AUTHDOMAIN`, `*_DATABASEURL`, `*_PROJECTID`, `*_STORAGEBUCKET`, `*_MESSAGINGSENDERID` and `*_APPID` are provided by the Firebase project you created.
Overall comment on these keys/values, the current description does not include enough info for me to know where to find them. E.g. provided by Firebase: where can I find them though?

2020-12-13 02:25 UTC, albinencio commented on README.md
> +All the variables that start with `REACT_APP_` are imported by CRA in our web app, they are the credentials we need to initialize Firebase app using Firebase SDK.
Where are they imported/where can I find them? Same below.

2020-12-13 02:25 UTC, albinencio commented on README.md
> +## Code/JSDoc
I would move this right after architecture. Basically, Architecture, Documentation Links, then Setup.

2020-12-13 02:46 UTC, Joyfal commented on README.md
> +## Setup
No matter what, they need to create a Firebase app of their own because they do not have access to our environment files.

2020-12-14 06:09 UTC, macedo22 requested changes
Great work! Some suggestions on wording and reorganizing a bit

2020-12-14 06:09 UTC, macedo22 commented on README.md
> +Launches the test runner in the interactive watch mode.\
maybe specify that this is specifically for running our Jest/unit tests, because this doesn't run our entire test suite

2020-12-14 06:09 UTC, macedo22 commented on README.md
> +## Code/JSDoc
I think it looks cleaner as a heading if we don't have a "/". Maybe do "Code and JS Doc Documentation"or "Code Documentation" or something like that

2020-12-14 06:09 UTC, macedo22 commented on README.md
> +Learn how to config JSDoc [here](https://jsdoc.app/about-configuring-jsdoc.html).
config --> configure

2020-12-14 06:09 UTC, macedo22 commented on README.md
> +For reference, you can look at our `jsdoc.json` in root directory for our own configuration of JSDoc.
""in **the** root..."

2020-12-14 06:09 UTC, macedo22 commented on README.md
> +We use [Jest](https://jestjs.io/docs/en/tutorial-react), combined with [testing-library](https://testing-library.com/docs/react-testing-library/example-intro/) for unit testing.
testing-library --> react-testing-library

2020-12-14 06:09 UTC, macedo22 commented on README.md
> +For our E2E tests, we decided to go with [Cypress](https://docs.cypress.io/guides/overview/why-cypress.html#In-a-nutshell) because it's well-documented and provides good support for asynchronous test
"... and **is** easy to setup"

2020-12-14 06:09 UTC, macedo22 commented on README.md
> +It's worth mentioning that since E2E tests require talking to the actual backend server (in our case, this is Firebase), we also need to setup environment variables so that Cypress can test Firebase
detail --> detailed

2020-12-14 06:09 UTC, macedo22 commented on README.md
> +For reference, you can look at our `cypress.json` in root directory for our own configuration of Cypress.
"... in **the** root..."

2020-12-14 06:09 UTC, macedo22 commented on README.md
> +We combined both Jest and Cypress test coverages so that it truely reflects our comprehensive code coverage. If interested, please take a look at our [test coverage workflow](.github/workflows/test_c
truely --> truly

2020-12-14 06:09 UTC, macedo22 commented on README.md
> +The combined coverage report is also hosted via GitHub Pages [here](https://ucsd-mashed.github.io/TaterTalkCoverage/).
Do you think we should say anything about code climate? We have a repo, it's part of our workflow, and it shows our code maintainability

2020-12-14 06:19 UTC, macedo22 commented on README.md
> +After setting up the environment files, you should install all the project dependencies by doing `yarn install`.
I also saw you updated the heading titles a bit, so with this suggestion here, the point is to move the "Scripts" section one level up so it's not nested within the instructions for extending the project

2020-12-14 06:23 UTC, macedo22 commented on README.md
> +After setting up the environment files, you should install all the project dependencies by doing `yarn install`.
And by "up" I mean from ### -> ##

2020-12-15 00:55 UTC, czhou29 commented on README.md
> +The combined coverage report is also hosted via GitHub Pages [here](https://ucsd-mashed.github.io/TaterTalkCoverage/).
Jason said we have a code climate badge, which might be enough for others to know the current maintainability.

2020-12-15 05:11 UTC, macedo22 requested changes
Some comments regarding making things more clear for someone wanting to use our project

2020-12-15 05:11 UTC, macedo22 commented on README.md
> +After setting up the environment files, you should install all the project dependencies by doing `yarn install`. Once the installation is done, you should be able to utilize the commands in the Scrip
there may be a better way to say these things, and honestly it would be good for us to spell our what each workflow is, but I think something like this is okay for now and we can be more thorough later if we have time, or link our workflow diagram or something

2020-12-15 05:14 UTC, macedo22 commented on README.md
> +After setting up the environment files, you should install all the project dependencies by doing `yarn install`. Once the installation is done, you should be able to utilize the commands in the Scrip
To be honest, that workflow section should probably be at the level of the Scripts because it's useful for a new developer to know, too, but I'll defer to you to figure out what might make most sense

2020-12-15 05:18 UTC, macedo22 requested changes

2020-12-15 05:18 UTC, macedo22 commented on README.md
> +
Also, if we add this workflow section (mentioned below) as a step (which I think we should), then we should probably move this line ("After setting up....") to _after_ the Workflows section, slightly modified, like:

### Environment files
### Workflow setup
### After setting up the environment files and your workflow files, you should install all the project dependencies by doing `yarn install`. Once the installation is done, you should be able to utilize the commands in the Scripts section below.
## Scripts

2020-12-15 06:16 UTC, macedo22 requested changes

2020-12-15 06:16 UTC, macedo22 commented on README.md
> +# TaterTalk
Also, I'm not sure where is best, but we should add a link to both the production and development apps. Right now, we have the production one in the repo description, but we're not really using it, and I think it's useful to add links to both somewhere in this README

2020-12-16 05:36 UTC, albinencio requested changes
I skimmed through Alex's comments and I left comments where needed. Please try to address these asap if you can. We can then merge before the demo and then make more edits later.

2020-12-16 05:36 UTC, albinencio commented on README.md
> +# TaterTalk
Agreed. We should have it right before the Architecture section, so it is easy to find if someone just wants to access.

2020-12-16 05:36 UTC, albinencio commented on README.md
> +The combined coverage report is also hosted via GitHub Pages [here](https://ucsd-mashed.github.io/TaterTalkCoverage/).
Agreed, adding a sentence about code climate would just be duplicating links.

2020-12-16 07:00 UTC, Joyfal commented on README.md
> +After creating your own Firebase app, you have to change the corresponding project id in this file.
Added explanation here.

2020-12-16 07:01 UTC, Joyfal commented on README.md
> +If you are not part of the team and would like to create an app of your own, you should first create a Firebase app [here](https://firebase.google.com/).
I don't want to add it here because we have it in the steps section, it would just be duplicates. I will change the steps sections slightly.

2020-12-16 07:02 UTC, Joyfal commented on README.md
> +In order to run this app in full capacity, you will also need to add your own configuration files as explained below.
Same comment, we explained it in steps section.

2020-12-16 07:10 UTC, Joyfal commented on README.md
> +However, you don't have to create two apps since you may just want to deploy only one branch, and then you can ignore all the instructions related to the development environment and `dev` branch.
I will revise this.

2020-12-16 07:15 UTC, Joyfal commented on README.md
> +After setting up the environment files, you should install all the project dependencies by doing `yarn install`. Once the installation is done, you should be able to utilize the commands in the Scrip
Good idea, added!

2020-12-16 07:18 UTC, Joyfal commented on README.md
> +# TaterTalk
We should not show the beta app link, they are not meant for show. They should be transparent to outsiders.

2020-12-16 10:28 UTC, macedo22 commented on README.md
> +If you are not part of the team and would like to create an app of your own, you should first create a Firebase app [here](https://firebase.google.com/).
I really like the change to the steps! Good solution

2020-12-16 10:48 UTC, macedo22 commented on README.md
> +# TaterTalk
I see your point this. I do think, however, that maybe we can discuss in our group meeting whether we think we should link the prod and/or beta apps in the description. If we don't want outside people to easily see the beta app (though, they can figure out the URL from our workflows), then let's be sure that we also provide the link to the beta app to the professor and Sander when we provide the `.env.dev` and `serviceAccount.json` files. I'm still an advocate of the README at least having a link to the production app or saying the link is in the repo description (just for clarity purposes), but since it's in the repo description, I also don't think it's *necessary*. We can find out if people have different opinions about what to link in the README, and I'm good with whatever we decide. For now since we need to get this PR in for recording, I'm good leaving as-is and optionally adding in link(s) later based on what we decide.

2020-12-16 10:51 UTC, macedo22 approved these changes
There are still a few nitpicky edits to make, as well as adding in links to our artifacts and diagrams, but I think it's important that we get this iteration in before recording, so I think that can wait.

I know there was a lot of change requests with this one, so thanks for your continued work and input on the suggestions! This is looking really great

@albinencio depending on which sections of the video we expect the README to show up in, I'm thinking we can figure out what to do about the `TODO` sections. I think we'll either need to push a simple PR tomorrow that just removes these sections before recording (so it looks clean), or we'll need to push a simple-to-moderate PR tomorrow in the early evening to fill in these two sections. We can talk more about this on slack, just wanted to share why I was approving this even though it has the "TODO"s still there.

2020-12-16 10:59 UTC, macedo22 commented
@Joyfal when you get a chance, can you update this with `dev`? I think the merge will be fine because it is only one file you're updating, but I didn't want to mess with your branch without your knowledge :)

2020-12-17 00:48 UTC, albinencio approved these changes
Approving to merge. We can make more edits later.

2020-12-17 00:55 UTC, merged