Dy format code style
UCSD-MASHED/chatapp pull request #55
Opened 2020-12-13 00:23 UTC by InnocenceD

## Checklist

- [ ] Did you write tests for your code?
- [ ] Did all the tests pass locally?

## Trello Ticket

https://trello.com/c/ThLJnTSd/83-edit-function-ordering-and-comments
https://trello.com/c/zUVa60fW/95-incorporate-api-doc-in-jsdoc

## Short Description

What does this PR contain?

## Reviewer Notes

Anything special you want the reviewer to know?

2020-12-14 02:09 UTC, macedo22 requested changes
Nice work! Most of my comments are regarding places where I think one of our backend API types should be linked where they're not. Outside of that, just a couple comments on wording. Thanks for adding these component headers!!

2020-12-14 03:03 UTC, InnocenceD commented on src/modules/CreateUser.js
> +   * @param {_GoogleUser} googleUser - google user to be found in database
The type is defined in the front so I don't want duplicates in description.

2020-12-14 03:03 UTC, InnocenceD commented on src/modules/Login.js
> +   * @param {_GoogleUser} googleUser - google user to be found in database
The type is defined in the front so I don't want duplicates in description.

2020-12-14 03:03 UTC, InnocenceD commented on src/modules/Login.js
> +   * @param {_GoogleUser} googleUser - google user to be logged in and redirected
The type is defined in the front so I don't want duplicates in description.

2020-12-14 06:36 UTC, macedo22 commented on src/modules/Types.js
> + */
@InnocenceD Also note that this affects the update to the database schema

2020-12-14 22:08 UTC, InnocenceD commented on src/modules/ChatRoom.js
> +   * Fetch the list of [message]{@link _Message} of the chat room
I linked message here because we don't have any message parameters or returns in this function; but we do have room linked as the parameter the next line so I don't want to show duplicate links. Let me know what you think and I'm open for changes.

2020-12-14 22:09 UTC, InnocenceD commented on src/modules/ChatRoom.js
> +   * Fetch the list of [message]{@link _Message} of the chat room
If we don't link message in descriptions, we won't have any links to message since we don't pass it as parameter nor return it. So the type definition will be completely useless.

2020-12-14 22:11 UTC, InnocenceD commented on src/modules/ChatRoom.js
> +   * Update user timestamp and append [message]{@link _Message} to room of messages.
I linked message here because we don't have any message parameters or returns in this function; but we do have room linked as the parameter the next line so I don't want to show duplicate links. Let me know what you think and I'm open for changes.

2020-12-14 22:23 UTC, InnocenceD commented on src/modules/Types.js
> + */
What name do we give to this field? Firestore does not give it a name and API doc says "typer" for this field.

2020-12-15 03:51 UTC, macedo22 commented on src/modules/ChatRoom.js
> +   * Fetch the list of [message]{@link _Message} of the chat room
I'm happy going with whatever you think makes sense! I just wanted to make sure I pointed it out. Feel free to update it or leave as-is and resolve this thread

2020-12-15 03:51 UTC, macedo22 commented on src/modules/ChatRoom.js
> +   * Update user timestamp and append [message]{@link _Message} to room of messages.
I'm happy going with whatever you think makes sense! I just wanted to make sure I pointed it out. Feel free to update it or leave as-is and resolve this thread

2020-12-15 03:51 UTC, macedo22 commented on src/modules/Types.js
> + */
I'm not sure, myself. I'll ask on slack

2020-12-16 08:15 UTC, macedo22 commented
@InnocenceD this looks great, and it looks like everything was addressed. One thing I thought of that I think could be great if it's something that we know how to do easily, but let me know if it would be difficult or not worth the effort - is there a way that we could add a description at the top of `globals.html` to describe what the page is? I'm imagining being a new developer or someone trying to understand our code base, seeing this, and the point of the page/types not being super clear. Could we add a short description at the top that is something like: "This page documents types that we define to describe data stored on our database. We define types for users' Google account information, as well as the users, chat rooms, and messages that we store." Or if you have a better way of writing it, even better! I just wrote this very quickly. Let me know your thoughts. We could alternatively write a very short description for each type, but I think this would be fine.

2020-12-16 11:27 UTC, InnocenceD commented
> @InnocenceD this looks great, and it looks like everything was addressed. One thing I thought of that I think could be great if it's something that we know how to do easily, but let me know if it would be difficult or not worth the effort - is there a way that we could add a description at the top of `globals.html` to describe what the page is? I'm imagining being a new developer or someone trying to understand our code base, seeing this, and the point of the page/types not being super clear. Could we add a short description at the top that is something like: "This page documents types that we define to describe data stored on our database. We define types for users' Google account information, as well as the users, chat rooms, and messages that we store." Or if you have a better way of writing it, even better! I just wrote this very quickly. Let me know your thoughts. We could alternatively write a very short description for each type, but I don't think that level of detail is necessary.
> 
> If we can't do it, I'm happy to approve, but if we can, let me know when you've added the change 👍

I did some research and could not find a way to add any description there. If we want, we can do it later in a separate PR.

2020-12-16 12:39 UTC, macedo22 commented
@InnocenceD Sounds good, awesome work on all of this

2020-12-16 12:41 UTC, macedo22 approved these changes

2020-12-16 22:31 UTC, merged